import { 
  LayoutDashboard, 
  AppWindow, 
  Building2, 
  Users, 
  History, 
  Settings, 
  RefreshCw,
  Zap,
  Truck,
  CheckCircle2,
  GraduationCap,
  LogOut,
  ChevronRight,
  Plus,
  HelpCircle,
  FileEdit,
  Trash2,
  Search,
  FileText,
  Eye,
  EyeOff,
  AlertCircle,
  ArrowLeft,
  ExternalLink,
  Globe,
  Lock,
  Image as ImageIcon
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Apps: AppWindow,
  Departments: Building2,
  Users: Users,
  Logs: History,
  Settings: Settings,
  Sync: RefreshCw,
  Shakti: Zap,
  Freight: Truck,
  Check: CheckCircle2,
  Training: GraduationCap,
  Logout: LogOut,
  ChevronRight: ChevronRight,
  Plus: Plus,
  Help: HelpCircle,
  Edit: FileEdit,
  Trash: Trash2,
  Search: Search,
  File: FileText,
  Eye: Eye,
  EyeOff: EyeOff,
  Alert: AlertCircle,
  Back: ArrowLeft,
  External: ExternalLink,
  Globe: Globe,
  Lock: Lock,
  Image: ImageIcon
};
